# 0. Data Ingestion

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
business_units = pd.read_csv('data/Business_Units.csv')
customer_service = pd.read_csv('data/Customer_Service.csv')
customers = pd.read_csv('data/Customers.csv')
group_operations = pd.read_csv('data/Group_Operations.csv')
inventory_history = pd.read_csv('data/Inventory_History.csv')
locations = pd.read_csv('data/Locations.csv')
machine_downtime = pd.read_csv('data/Machine_Downtime.csv')
marketing = pd.read_csv('data/Marketing.csv')
materials = pd.read_csv('data/Materials.csv')
printing_batches = pd.read_csv('data/Printing_Batches.csv')
                                                    # Product Bill of Materials (Product BOM) is the master, 
product_bom = pd.read_csv('data/Product_BOM.csv')   # centralized list of all raw materials, components, assemblies,
                                                    # parts, and quantities required to build a finished product.
product_master = pd.read_csv('data/Product_Master.csv')
production_orders = pd.read_csv('data/Production_Orders.csv')
purchase_orders = pd.read_csv('data/Purchase_Orders.csv')
quality = pd.read_csv('data/Quality.csv')
sales_transactions = pd.read_csv('data/Sales_Transactions.csv', index_col=0)
suppliers = pd.read_csv('data/Suppliers.csv')
web_traffic_daily = pd.read_csv('data/Web_Traffic_Daily.csv')

In [4]:
dataframes = {
    'sales_transactions': sales_transactions,
    'printing_batches': printing_batches,
    'quality': quality,
    'product_master': product_master,
    'production_orders': production_orders,
    'inventory_history': inventory_history,
    'product_bom': product_bom,
    'business_units': business_units,
    'customer_service': customer_service,
    'customers': customers,
    'group_operations': group_operations,
    'locations': locations,
    'machine_downtime': machine_downtime,
    'marketing': marketing,
    'materials': materials,
    'purchase_orders': purchase_orders,
    'suppliers': suppliers,
    'web_traffic_daily': web_traffic_daily}

for frame_name, df in dataframes.items():
    print(f"DataFrame: {frame_name}")
    display(df.head(5))
    print("\n")

DataFrame: sales_transactions

,Invoice_ID,Order_Date,Month_Key,Location_ID,Location_Name,Channel,Customer_ID,Customer_Type,Customer_Governorate,Product_ID,...,Estimated_COGS_EGP,Gross_Profit_EGP,Gross_Margin_Pct,Payment_Method,Returned,Return_Date,Return_Reason,Refund_Value_EGP,Quality_Related_Return,Data_Class
Row_ID,,,,,,,,,,,,,,,,,,,,,
0,INV0000001,5/11/2024,2024-05,LOC002,LEO MODA Online Store,Online,C18976,Retail,Cairo,P059,...,247.57,82.23,0.2493,Wallet,No,NaN,No return,0.0,No,Modeled training transaction anchored to publi...
1,INV0000002,7/31/2025,2025-07,LOC001,LEO MODA - Sidi Bishr Store,Retail,C22543,Retail,Alexandria,P038,...,163.31,67.89,0.2936,Card,No,NaN,No return,0.0,No,Modeled training transaction anchored to publi...
2,INV0000003,5/23/2026,2026-05,LOC003,El-Sharnouby Wholesale Desk,Wholesale,C13351,Wholesale,Alexandria,P028,...,4301.71,512.69,0.1065,Cash,No,NaN,No return,0.0,No,Modeled training transaction anchored to publi...
3,INV0000004,6/5/2024,2024-06,LOC003,El-Sharnouby Wholesale Desk,Wholesale,C21377,Wholesale,Dakahlia,P004,...,10451.13,907.59,0.0799,Bank Transfer,No,NaN,No return,0.0,No,Modeled training transaction anchored to publi...
4,INV0000005,12/28/2025,2025-12,LOC001,LEO MODA - Sidi Bishr Store,Retail,C21499,Retail,Alexandria,P024,...,186.16,53.04,0.2217,Cash,No,NaN,No return,0.0,No,Modeled training transaction anchored to publi...

DataFrame: printing_batches

,Print_Batch_ID,Product_ID,Product_Name,Print_Date,Print_Type,Machine_ID,Planned_Qty,Printed_Qty,Good_Qty,Rejected_Qty,Reprint_Qty,Defect_Type,Ink_or_Consumable_Cost_EGP,Rework_Cost_EGP,Data_Class
0,PR00001,P015,Girls' summer pajamas-Stay cool,10/29/2023,Digital,PR-M02,3240,3119,3055,64,31,NaN,12570.15,178.57,Modeled print operation
1,PR00002,P051,Ice cream - بيجامة حريمي صيفي2024,5/13/2025,Water-Based,PR-M02,949,926,882,44,31,Curing,6152.74,244.02,Modeled print operation
2,PR00003,P015,Girls' summer pajamas-Stay cool,7/20/2025,Heat Transfer,PR-M05,5242,5185,5007,178,81,Curing,24019.22,375.21,Modeled print operation
3,PR00004,P037,Girls' sweatshirt-Flower,12/14/2023,Heat Transfer,PR-M04,4682,4582,4495,87,73,NaN,24506.50,552.16,Modeled print operation
4,PR00005,P043,Girls' autumn pajamas-Snow White,12/11/2023,Digital,PR-M03,5480,5521,5444,77,68,Registration,15642.27,425.81,Modeled print operation

DataFrame: quality

,QC_ID,Inspection_Date,Product_ID,Product_Name,Stage,Inspected_Qty,Passed_Qty,Rejected_Qty,Defect_Type,Root_Cause,Estimated_Loss_EGP,Data_Class
0,QC000001,3/9/2026,P049,Fuchsia - طقم تيشيرت وشورت اطفال صيفي,Fabric,40,39,1,NaN,No significant issue,239.99,Modeled QC inspection
1,QC000002,9/21/2025,P027,Girls' pajamas - I'm Just a girl,Finishing,629,613,16,Color Misalignment,Operator method,1689.62,Modeled QC inspection
2,QC000003,8/21/2024,P008,Summer children's boys-SpongeBob,Finishing,577,553,24,Print Cracking,No significant issue,4343.01,Modeled QC inspection
3,QC000004,4/10/2024,P006,Summer children's boys-Sonic,Cutting,732,707,25,Size Variance,Machine calibration,4912.69,Modeled QC inspection
4,QC000005,5/18/2024,P050,Yellow - طقم تيشيرت وشورت اطفال صيفي,Final,189,186,3,Ink Smudge,Material variation,730.95,Modeled QC inspection

DataFrame: product_master

,Product_ID,SKU,Product_Name,Brand,Product_Family,Gender,Audience,Catalog_Season,Sizes,Public_Retail_Price_EGP,Public_Catalog_Source,Verification_Class
0,P001,26115-8,Summer children's girls-Happy,Leo Moda,Pajamas/Homewear,Girls,Kids,Summer 2026,"4, 6, 8, 10, 12",348,https://leo.moda/shop/,Public catalog product / public retail price
1,P002,26115-6,Summer children's girls-turtle,Leo Moda,Pajamas/Homewear,Girls,Kids,Summer 2026,"4, 6, 8, 10, 12",348,https://leo.moda/shop/,Public catalog product / public retail price
2,P003,26115-5,Summer children's girls-Hello kitty Rose & tur...,Leo Moda,Pajamas/Homewear,Girls,Kids,Summer 2026,"4, 6, 8, 10, 12",348,https://leo.moda/shop/,Public catalog product / public retail price
3,P004,26115-7,Summer children's girls-Hello kitty black&white,Leo Moda,Pajamas/Homewear,Girls,Kids,Summer 2026,"4, 6, 8, 10, 12",348,https://leo.moda/shop/,Public catalog product / public retail price
4,P005,26115-2,Summer children's boys-Black and orange,Leo Moda,Pajamas/Homewear,Boys,Kids,Summer 2026,"4, 6, 8, 10, 12",348,https://leo.moda/shop/,Public catalog product / public retail price

DataFrame: production_orders

,Production_Order_ID,Product_ID,Product_Name,Start_Date,Due_Date,Completion_Date,Planned_Qty,Produced_Qty,Good_Qty,Rejected_Qty,Line_ID,Efficiency_Pct,Delay_Days,Primary_Bottleneck,Overtime_Hours,Data_Class
0,PO00001,P035,Girls' sweatshirt-Fuchsia,11/11/2025,11/22/2025,11/22/2025,1228,1140,1124,16,LINE-05,81.1,0,NaN,4.5,Modeled factory production order
1,PO00002,P055,Scooby-Doo - بيجامة حريمي صيفي2024,9/1/2025,9/19/2025,9/19/2025,1215,1215,1185,30,LINE-04,89.7,0,NaN,0.5,Modeled factory production order
2,PO00003,P001,Summer children's girls-Happy,3/22/2025,4/8/2025,4/15/2025,613,580,562,18,LINE-04,86.5,7,Finishing,14.7,Modeled factory production order
3,PO00004,P001,Summer children's girls-Happy,5/6/2024,5/22/2024,5/22/2024,4533,3640,3557,83,LINE-03,72.2,0,NaN,3.6,Modeled factory production order
4,PO00005,P045,Girls' autumn pajamas-Stitch,8/8/2025,8/22/2025,8/22/2025,987,756,746,10,LINE-02,72.5,0,NaN,13.6,Modeled factory production order

DataFrame: inventory_history

,Snapshot_Month,Location_ID,Location_Name,Product_ID,SKU,Product_Name,Opening_Stock,Received_Qty,Sold_Qty,Returned_Qty,Damaged_Qty,Closing_Stock,Avg_Daily_Sales_90D,Safety_Stock_Units,Reorder_Point_Units,Supplier_Lead_Time_Days,Days_of_Cover,Stockout_Days_In_Month,Data_Class
0,10/1/2023,LOC001,LEO MODA - Sidi Bishr Store,P001,26115-8,Summer children's girls-Happy,176,39,42,3,0,176,1.38,5,12,5,127.5,0,Modeled inventory history - no forecast column...
1,11/1/2023,LOC001,LEO MODA - Sidi Bishr Store,P001,26115-8,Summer children's girls-Happy,176,65,62,4,1,182,1.71,23,59,21,106.4,0,Modeled inventory history - no forecast column...
2,12/1/2023,LOC001,LEO MODA - Sidi Bishr Store,P001,26115-8,Summer children's girls-Happy,182,54,61,1,1,175,1.81,25,63,21,96.7,0,Modeled inventory history - no forecast column...
3,1/1/2024,LOC001,LEO MODA - Sidi Bishr Store,P001,26115-8,Summer children's girls-Happy,175,35,42,1,0,169,1.81,12,30,10,93.4,0,Modeled inventory history - no forecast column...
4,2/1/2024,LOC001,LEO MODA - Sidi Bishr Store,P001,26115-8,Summer children's girls-Happy,169,28,31,1,0,167,1.47,7,17,7,113.6,0,Modeled inventory history - no forecast column...

DataFrame: product_bom

,Product_ID,Product_Name,Material_ID,Material_Name,Required_Per_Unit,Unit,Data_Class
0,P001,Summer children's girls-Happy,M001,Single Jersey Cotton 160 GSM,1.040,meter,Modeled BOM for training
1,P001,Summer children's girls-Happy,M006,Sewing Thread,0.032,cone,Modeled BOM for training
2,P001,Summer children's girls-Happy,M007,Neck Label,1.000,piece,Modeled BOM for training
3,P001,Summer children's girls-Happy,M008,Care Label,1.000,piece,Modeled BOM for training
4,P001,Summer children's girls-Happy,M009,Poly Bag,1.000,piece,Modeled BOM for training

DataFrame: business_units

,Business_Unit,Function,Public_Capacity,Source_URL,Verification_Class
0,LEO DESIGN,"Fashion design, pattern making, 3D visualization",Not publicly stated,https://www.el-sharnouby.com/,Public company fact
1,LEO TEX,Woven fabric manufacturing,Integrated textile manufacturing; exact capaci...,https://www.el-sharnouby.com/services,Public company fact
2,LEO PRODUCTION HUB,Garment manufacturing,"Up to 5,000 pieces/day",https://www.el-sharnouby.com/services,Public company fact
3,LEO PRINT,Textile and garment printing,"Up to 20,000 garments/day and 6,000 fabric met...",https://www.el-sharnouby.com/services,Public company fact
4,LEO MODA,"Retail, online and wholesale apparel brand",Delivery across Egypt; retail + wholesale chan...,https://leo.moda/,Public company fact

DataFrame: customer_service

,Ticket_ID,Open_Date,Channel,Issue_Type,First_Response_Minutes,Resolution_Hours,Resolved,CSAT_1_to_5,Data_Class
0,TKT00001,2/2/2025,WhatsApp,Return request,6.5,9.3,Yes,2,Modeled customer service interaction
1,TKT00002,1/1/2024,Instagram,Order status,21.8,10.1,Yes,4,Modeled customer service interaction
2,TKT00003,3/21/2026,WhatsApp,Product quality,7.0,7.7,Yes,5,Modeled customer service interaction
3,TKT00004,6/15/2025,Phone,Product quality,4.7,26.3,Yes,4,Modeled customer service interaction
4,TKT00005,7/5/2026,Website,Exchange request,14.6,14.0,Yes,5,Modeled customer service interaction

DataFrame: customers

,Customer_ID,Customer_Type,Governorate,Age_Band,Gender,Join_Date,Acquisition_Channel,Consent_Status,Data_Class
0,C00001,Retail,Dakahlia,45-54,Male,2/22/2026,Organic Social,Not opted-in,Modeled/anonymized training customer - not act...
1,C00002,Retail,Beheira,35-44,Male,9/30/2024,Direct / WhatsApp,Opted-in,Modeled/anonymized training customer - not act...
2,C00003,Retail,Dakahlia,25-34,Female,6/27/2025,Organic Social,Opted-in,Modeled/anonymized training customer - not act...
3,C00004,Wholesale,Port Said,Business,Business,9/27/2024,Wholesale Sales,Opted-in,Modeled/anonymized training customer - not act...
4,C00005,Retail,Gharbia,55+,Female,2/7/2025,Paid Social,Not opted-in,Modeled/anonymized training customer - not act...

DataFrame: group_operations

,Month,Business_Unit,Primary_KPI,Volume,Operational_Efficiency_Pct,Open_Issues_Count,Data_Class
0,10/1/2023,LEO DESIGN,Designs_Completed,48,85.1,2,Modeled monthly operational summary using publ...
1,10/1/2023,LEO TEX,Fabric_Meters,129278,91.5,6,Modeled monthly operational summary using publ...
2,10/1/2023,LEO PRODUCTION HUB,Garments_Produced,78490,88.5,9,Modeled monthly operational summary using publ...
3,10/1/2023,LEO PRINT,Print_Units,70454,86.7,1,Modeled monthly operational summary using publ...
4,10/1/2023,LEO MODA,Sales_Units,36484,87.6,1,Modeled monthly operational summary using publ...

DataFrame: locations

,Location_ID,Location_Name,Location_Type,Channel,Governorate,City,Public_Address,Source_URL,Verification_Class
0,LOC001,LEO MODA - Sidi Bishr Store,Retail Store,Retail,Alexandria,Sidi Bishr,"72C2+GXJ, Sidi Bishr Bahri, Montaza 2, Alexand...",https://leo.moda/our-stores/,Public store / address cross-checked from publ...
1,LOC002,LEO MODA Online Store,Digital Store,Online,Egypt,Nationwide,Online - delivery across Egypt,https://leo.moda/,Public channel
2,LOC003,El-Sharnouby Wholesale Desk,B2B / Wholesale,Wholesale,Alexandria,Zizinia,"5 Amin Yehia Street, Zizinia, Alexandria, Egypt",https://www.el-sharnouby.com/,Public HQ / wholesale inquiry channel
3,LOC004,El-Sharnouby Head Office,Head Office,Corporate,Alexandria,Zizinia,"5 Amin Yehia Street, Zizinia, Alexandria, Egypt",https://www.el-sharnouby.com/,Public HQ
4,LOC005,LEO Production Hub,Factory / Production,Operations,Alexandria,Alexandria,"Alexandria, Egypt",https://www.el-sharnouby.com/services,Public business unit; exact facility address n...

DataFrame: machine_downtime

,Downtime_ID,Date,Machine_ID,Business_Area,Downtime_Hours,Reason,Planned,Data_Class
0,DT00001,5/21/2025,CUT-01,Cutting,0.7,Planned maintenance,Yes,Modeled equipment event
1,DT00002,2/14/2026,PR-M03,Printing,0.8,Setup / changeover,No,Modeled equipment event
2,DT00003,4/11/2024,PR-M04,Printing,11.7,Setup / changeover,No,Modeled equipment event
3,DT00004,1/16/2026,PR-M01,Printing,0.7,Planned maintenance,Yes,Modeled equipment event
4,DT00005,10/6/2024,SEW-L01,Sewing,2.5,Material wait,No,Modeled equipment event

DataFrame: marketing

,Campaign_ID,Campaign_Name,Product_ID,Product_Name,Platform,Start_Date,End_Date,Spend_EGP,Impressions,Clicks,Landing_Page_Sessions,Orders_Attributed,Attributed_Revenue_EGP,Discount_Pct,Data_Class
0,CMP0001,Meta | Boys' summer pajamas-Wear your a | May24,P018,Boys' summer pajamas-Wear your attitude,Meta,5/24/2024,6/8/2024,24313,549466,6835,6835,103,41337.81,0.15,Modeled campaign performance - not actual medi...
1,CMP0002,TikTok | Girls' pajamas-Daylife+kuromi | Dec24,P029,Girls' pajamas-Daylife+kuromi,TikTok,12/24/2024,12/29/2024,25303,626807,13393,13393,193,95701.65,0.10,Modeled campaign performance - not actual medi...
2,CMP0003,Google | Boys' Autumn Pajamas-Loony Tunes | Oct25,P040,Boys' Autumn Pajamas-Loony Tunes,Google,10/22/2025,11/13/2025,47808,542947,17336,17336,881,353823.52,0.00,Modeled campaign performance - not actual medi...
3,CMP0004,Meta | Girls' summer pajamas-Stay cool | Mar24,P015,Girls' summer pajamas-Stay cool,Meta,3/26/2024,4/9/2024,55766,795931,15690,15690,252,98952.32,0.20,Modeled campaign performance - not actual medi...
4,CMP0005,Meta | Fuchsia - طقم تيشيرت وشورت اطفال | Mar25,P049,Fuchsia - طقم تيشيرت وشورت اطفال صيفي,Meta,3/7/2025,3/19/2025,39530,597865,13586,13586,197,107103.87,0.20,Modeled campaign performance - not actual medi...

DataFrame: materials

,Material_ID,Material_Name,Unit,Material_Category,Standard_Lead_Time_Days,Data_Class
0,M001,Single Jersey Cotton 160 GSM,meter,Fabric,10,Modeled operational material master
1,M002,Single Jersey Cotton 180 GSM,meter,Fabric,14,Modeled operational material master
2,M003,Rib Cotton,meter,Fabric,10,Modeled operational material master
3,M004,Summer Melton,meter,Fabric,10,Modeled operational material master
4,M005,Elastic Band,meter,Trims,7,Modeled operational material master

DataFrame: purchase_orders

,PO_ID,Order_Date,Supplier_ID,Material_ID,Material_Name,Unit,Ordered_Qty,Unit_Cost_EGP,Promised_Date,Actual_Receipt_Date,Accepted_Qty,Rejected_Qty,Data_Class
0,MPO00001,2/2/2025,SUP04,M010,Carton Box,piece,3880,8.07,2/16/2025,2/21/2025,3777,103,Modeled procurement / supplier performance
1,MPO00002,10/18/2025,SUP07,M001,Single Jersey Cotton 160 GSM,meter,1332,85.55,10/23/2025,10/23/2025,1309,23,Modeled procurement / supplier performance
2,MPO00003,2/17/2024,SUP04,M012,Heat Transfer Film,sheet,13868,10.79,2/24/2024,2/24/2024,13582,286,Modeled procurement / supplier performance
3,MPO00004,8/24/2024,SUP03,M011,Water-Based Ink,kg,5474,315.44,9/7/2024,9/10/2024,5329,145,Modeled procurement / supplier performance
4,MPO00005,4/8/2026,SUP08,M004,Summer Melton,meter,4501,114.01,4/13/2026,4/13/2026,4429,72,Modeled procurement / supplier performance

DataFrame: suppliers

,Supplier_ID,Supplier_Name,Primary_Category,Governorate,Payment_Terms_Days,Contracted,Data_Class
0,SUP01,Approved Supplier 01 (anonymized),Packaging,Beheira,45,No,Modeled training record - supplier identity an...
1,SUP02,Approved Supplier 02 (anonymized),Trims,Alexandria,15,Yes,Modeled training record - supplier identity an...
2,SUP03,Approved Supplier 03 (anonymized),Fabric,Gharbia,45,No,Modeled training record - supplier identity an...
3,SUP04,Approved Supplier 04 (anonymized),Printing Consumables,Beheira,60,Yes,Modeled training record - supplier identity an...
4,SUP05,Approved Supplier 05 (anonymized),Fabric,Cairo,45,No,Modeled training record - supplier identity an...

DataFrame: web_traffic_daily

,Date,Sessions,Users,New_User_Pct,Mobile_Pct,Add_To_Cart_Rate,Checkout_Rate,Orders,Conversion_Rate,Avg_Page_Load_Sec,Data_Class
0,10/1/2023,1403,1150,0.631,0.782,0.1067,0.0600,43,0.0308,3.27,Modeled digital analytics training data
1,10/2/2023,1150,943,0.624,0.732,0.1069,0.0483,33,0.0295,3.39,Modeled digital analytics training data
2,10/3/2023,1071,878,0.641,0.731,0.1126,0.0483,29,0.0275,2.89,Modeled digital analytics training data
3,10/4/2023,1183,970,0.609,0.827,0.0777,0.0347,26,0.0225,2.19,Modeled digital analytics training data
4,10/5/2023,1072,879,0.623,0.788,0.1035,0.0527,29,0.0278,3.37,Modeled digital analytics training data

In [5]:
for frame_name, df in dataframes.items():
    print(f"DataFrame: {frame_name}")
    display(df.dtypes)
    print("\n")

DataFrame: sales_transactions

Invoice_ID                    str
Order_Date                    str
Month_Key                     str
Location_ID                   str
Location_Name                 str
Channel                       str
Customer_ID                   str
Customer_Type                 str
Customer_Governorate          str
Product_ID                    str
SKU                           str
Product_Name                  str
Product_Family                str
Size                          str
Quantity                    int64
List_Price_EGP              int64
Discount_Pct              float64
Gross_Sales_EGP             int64
Net_Sales_EGP             float64
Estimated_COGS_EGP        float64
Gross_Profit_EGP          float64
Gross_Margin_Pct          float64
Payment_Method                str
Returned                      str
Return_Date                   str
Return_Reason                 str
Refund_Value_EGP          float64
Quality_Related_Return        str
Data_Class                    str
dtype: object

DataFrame: printing_batches

Print_Batch_ID                    str
Product_ID                        str
Product_Name                      str
Print_Date                        str
Print_Type                        str
Machine_ID                        str
Planned_Qty                     int64
Printed_Qty                     int64
Good_Qty                        int64
Rejected_Qty                    int64
Reprint_Qty                     int64
Defect_Type                       str
Ink_or_Consumable_Cost_EGP    float64
Rework_Cost_EGP               float64
Data_Class                        str
dtype: object

DataFrame: quality

QC_ID                     str
Inspection_Date           str
Product_ID                str
Product_Name              str
Stage                     str
Inspected_Qty           int64
Passed_Qty              int64
Rejected_Qty            int64
Defect_Type               str
Root_Cause                str
Estimated_Loss_EGP    float64
Data_Class                str
dtype: object

DataFrame: product_master

Product_ID                   str
SKU                          str
Product_Name                 str
Brand                        str
Product_Family               str
Gender                       str
Audience                     str
Catalog_Season               str
Sizes                        str
Public_Retail_Price_EGP    int64
Public_Catalog_Source        str
Verification_Class           str
dtype: object

DataFrame: production_orders

Production_Order_ID        str
Product_ID                 str
Product_Name               str
Start_Date                 str
Due_Date                   str
Completion_Date            str
Planned_Qty              int64
Produced_Qty             int64
Good_Qty                 int64
Rejected_Qty             int64
Line_ID                    str
Efficiency_Pct         float64
Delay_Days               int64
Primary_Bottleneck         str
Overtime_Hours         float64
Data_Class                 str
dtype: object

DataFrame: inventory_history

Snapshot_Month                 str
Location_ID                    str
Location_Name                  str
Product_ID                     str
SKU                            str
Product_Name                   str
Opening_Stock                int64
Received_Qty                 int64
Sold_Qty                     int64
Returned_Qty                 int64
Damaged_Qty                  int64
Closing_Stock                int64
Avg_Daily_Sales_90D        float64
Safety_Stock_Units           int64
Reorder_Point_Units          int64
Supplier_Lead_Time_Days      int64
Days_of_Cover              float64
Stockout_Days_In_Month       int64
Data_Class                     str
dtype: object

DataFrame: product_bom

Product_ID               str
Product_Name             str
Material_ID              str
Material_Name            str
Required_Per_Unit    float64
Unit                     str
Data_Class               str
dtype: object

DataFrame: business_units

Business_Unit         str
Function              str
Public_Capacity       str
Source_URL            str
Verification_Class    str
dtype: object

DataFrame: customer_service

Ticket_ID                     str
Open_Date                     str
Channel                       str
Issue_Type                    str
First_Response_Minutes    float64
Resolution_Hours          float64
Resolved                      str
CSAT_1_to_5                 int64
Data_Class                    str
dtype: object

DataFrame: customers

Customer_ID            str
Customer_Type          str
Governorate            str
Age_Band               str
Gender                 str
Join_Date              str
Acquisition_Channel    str
Consent_Status         str
Data_Class             str
dtype: object

DataFrame: group_operations

Month                             str
Business_Unit                     str
Primary_KPI                       str
Volume                          int64
Operational_Efficiency_Pct    float64
Open_Issues_Count               int64
Data_Class                        str
dtype: object

DataFrame: locations

Location_ID           str
Location_Name         str
Location_Type         str
Channel               str
Governorate           str
City                  str
Public_Address        str
Source_URL            str
Verification_Class    str
dtype: object

DataFrame: machine_downtime

Downtime_ID           str
Date                  str
Machine_ID            str
Business_Area         str
Downtime_Hours    float64
Reason                str
Planned               str
Data_Class            str
dtype: object

DataFrame: marketing

Campaign_ID                   str
Campaign_Name                 str
Product_ID                    str
Product_Name                  str
Platform                      str
Start_Date                    str
End_Date                      str
Spend_EGP                   int64
Impressions                 int64
Clicks                      int64
Landing_Page_Sessions       int64
Orders_Attributed           int64
Attributed_Revenue_EGP    float64
Discount_Pct              float64
Data_Class                    str
dtype: object

DataFrame: materials

Material_ID                  str
Material_Name                str
Unit                         str
Material_Category            str
Standard_Lead_Time_Days    int64
Data_Class                   str
dtype: object

DataFrame: purchase_orders

PO_ID                      str
Order_Date                 str
Supplier_ID                str
Material_ID                str
Material_Name              str
Unit                       str
Ordered_Qty              int64
Unit_Cost_EGP          float64
Promised_Date              str
Actual_Receipt_Date        str
Accepted_Qty             int64
Rejected_Qty             int64
Data_Class                 str
dtype: object

DataFrame: suppliers

Supplier_ID             str
Supplier_Name           str
Primary_Category        str
Governorate             str
Payment_Terms_Days    int64
Contracted              str
Data_Class              str
dtype: object

DataFrame: web_traffic_daily

Date                     str
Sessions               int64
Users                  int64
New_User_Pct         float64
Mobile_Pct           float64
Add_To_Cart_Rate     float64
Checkout_Rate        float64
Orders                 int64
Conversion_Rate      float64
Avg_Page_Load_Sec    float64
Data_Class               str
dtype: object

In [10]:
to_date_columns = []
for frame_name, df in dataframes.items():
    for column in df.columns:
        if column[-4:] == 'Date':
            if column not in to_date_columns:    
                to_date_columns.append(column)
print('Columns with date values:', to_date_columns)

Columns with date values: ['Order_Date', 'Return_Date', 'Print_Date', 'Inspection_Date', 'Start_Date', 'Due_Date', 'Completion_Date', 'Open_Date', 'Join_Date', 'Date', 'End_Date', 'Promised_Date', 'Actual_Receipt_Date']

In [7]:
for frame_name, df in dataframes.items():
    for col in to_date_columns:
        if col in df.columns:
            df[col] = pd.to_datetime(df[col], errors='coerce')

In [9]:
print('ًُWe have data for',sales_transactions.Month_Key.unique().__len__(),'months' )

ًُWe have data for 36 months

In [8]:
sales_transactions.Invoice_ID.unique().__len__()

180000

In [11]:
check_price = pd.merge(sales_transactions, product_master, on='Product_ID')[['Public_Retail_Price_EGP','List_Price_EGP']]
check_price['Price_Difference'] = check_price['Public_Retail_Price_EGP'] - check_price['List_Price_EGP']
print('Price differences between public retail and list prices:', check_price['Price_Difference'].unique())

Price differences between public retail and list prices: [0]

# 1. Executive Sales & Profitability
* Revenue is growing, but management is unsure whether growth is converting into healthy gross profit across products and channels.
* Build an executive view of revenue, units, gross profit, margin, YoY/MoM growth, seasonality, product contribution, discount impact and clear management actions.

* Business question: Is revenue growth translating into healthy gross profit across products and channels?
* Target output: An executive view of sales, units, gross profit, margin, growth, seasonality, product contribution and discount impact.

In [10]:
sales_transactions
# returns/refunds are not reflected in net sales or profit

,Invoice_ID,Order_Date,Month_Key,Location_ID,Location_Name,Channel,Customer_ID,Customer_Type,Customer_Governorate,Product_ID,...,Estimated_COGS_EGP,Gross_Profit_EGP,Gross_Margin_Pct,Payment_Method,Returned,Return_Date,Return_Reason,Refund_Value_EGP,Quality_Related_Return,Data_Class
Row_ID,,,,,,,,,,,,,,,,,,,,,
0,INV0000001,2024-05-11,2024-05,LOC002,LEO MODA Online Store,Online,C18976,Retail,Cairo,P059,...,247.57,82.23,0.2493,Wallet,No,NaT,No return,0.0,No,Modeled training transaction anchored to publi...
1,INV0000002,2025-07-31,2025-07,LOC001,LEO MODA - Sidi Bishr Store,Retail,C22543,Retail,Alexandria,P038,...,163.31,67.89,0.2936,Card,No,NaT,No return,0.0,No,Modeled training transaction anchored to publi...
2,INV0000003,2026-05-23,2026-05,LOC003,El-Sharnouby Wholesale Desk,Wholesale,C13351,Wholesale,Alexandria,P028,...,4301.71,512.69,0.1065,Cash,No,NaT,No return,0.0,No,Modeled training transaction anchored to publi...
3,INV0000004,2024-06-05,2024-06,LOC003,El-Sharnouby Wholesale Desk,Wholesale,C21377,Wholesale,Dakahlia,P004,...,10451.13,907.59,0.0799,Bank Transfer,No,NaT,No return,0.0,No,Modeled training transaction anchored to publi...
4,INV0000005,2025-12-28,2025-12,LOC001,LEO MODA - Sidi Bishr Store,Retail,C21499,Retail,Alexandria,P024,...,186.16,53.04,0.2217,Cash,No,NaT,No return,0.0,No,Modeled training transaction anchored to publi...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179995,INV0179996,2026-07-11,2026-07,LOC002,LEO MODA Online Store,Online,C19390,Retail,Other,P006,...,170.52,107.88,0.3875,Cash,No,NaT,No return,0.0,No,Modeled training transaction anchored to publi...
179996,INV0179997,2025-04-06,2025-04,LOC002,LEO MODA Online Store,Online,C23903,Retail,Cairo,P054,...,216.95,171.05,0.4409,Card,No,NaT,No return,0.0,No,Modeled training transaction anchored to publi...
179997,INV0179998,2024-04-27,2024-04,LOC001,LEO MODA - Sidi Bishr Store,Retail,C23880,Retail,Dakahlia,P058,...,387.04,388.96,0.5012,Bank Transfer,No,NaT,No return,0.0,No,Modeled training transaction anchored to publi...
179998,INV0179999,2026-08-18,2026-08,LOC002,LEO MODA Online Store,Online,C24159,Retail,Cairo,P054,...,433.89,342.11,0.4409,Cash,No,NaT,No return,0.0,No,Modeled training transaction anchored to publi...
179999,INV0180000,2026-07-17,2026-07,LOC003,El-Sharnouby Wholesale Desk,Wholesale,C11646,Wholesale,Cairo,P003,...,6477.57,1039.23,0.1383,Bank Transfer,No,NaT,No return,0.0,No,Modeled training transaction anchored to publi...

## 1.1 MoM/YoY Growth

In [14]:
MoM_growth = sales_transactions.pivot_table(
    index='Month_Key', values=['Gross_Sales_EGP'],
    aggfunc='sum').sort_index()

MoM_growth['Gross_Sales_EGP_Growth_Pct'] = round(MoM_growth['Gross_Sales_EGP'].pct_change() * 100, 2) 

agg_cols = ['Net_Sales_EGP', 'Estimated_COGS_EGP', 'Gross_Profit_EGP', 'Refund_Value_EGP', 'Quantity']
for col in agg_cols:
    agg_index='Month_Key'
    MoM_growth[col] = sales_transactions.pivot_table(
                                    index=agg_index, values=[col],
                                    aggfunc='sum').sort_index()[col]
    MoM_growth[col] = round(MoM_growth[col], 2)
    if col == 'Net_Sales_EGP':
        MoM_growth[f'{col}_Growth_Pct'] = round(MoM_growth[col].pct_change() * 100, 2)
    if col == 'Gross_Profit_EGP':
        MoM_growth['Gross_Margin_Pct'] = round(MoM_growth['Gross_Profit_EGP'] / MoM_growth['Net_Sales_EGP'] * 100, 2)

MoM_growth.reset_index(inplace=True)
MoM_growth

,Month_Key,Gross_Sales_EGP,Gross_Sales_EGP_Growth_Pct,Net_Sales_EGP,Net_Sales_EGP_Growth_Pct,Estimated_COGS_EGP,Gross_Profit_EGP,Gross_Margin_Pct,Refund_Value_EGP,Quantity
0,2023-10,13766065,NaN,9663345.29,NaN,8104911.57,1558433.72,16.13,259935.61,36484
1,2023-11,15357356,11.56,10771256.46,11.47,9058963.09,1712293.37,15.90,258744.88,40007
2,2023-12,17511126,14.02,12277328.47,13.98,10352650.38,1924678.09,15.68,222007.26,45928
3,2024-01,13089177,-25.25,9172864.77,-25.29,7710873.35,1461991.42,15.94,123961.32,34495
4,2024-02,12575755,-3.92,8800097.31,-4.06,7416690.82,1383406.49,15.72,185201.12,32923
5,2024-03,14621476,16.27,10277634.17,16.79,8672554.17,1605080.00,15.62,276270.41,40500
6,2024-04,16395096,12.13,11486993.44,11.77,9801970.32,1685023.12,14.67,348578.82,46938
7,2024-05,16260687,-0.82,11421809.19,-0.57,9743340.66,1678468.53,14.70,284507.15,46803
8,2024-06,16845455,3.60,11792982.05,3.25,10051999.56,1740982.49,14.76,247795.94,48357
9,2024-07,18159990,7.80,12719754.24,7.86,10846808.50,1872945.74,14.72,244274.11,52210
10,2024-08,16567764,-8.77,11606488.48,-8.75,9902080.25,1704408.23,14.68,251017.17,47810
11,2024-09,13578705,-18.04,9533791.28,-17.86,8055666.68,1478124.60,15.50,221722.74,38090
12,2024-10,15847665,16.71,11076601.25,16.18,9308947.13,1767654.12,15.96,219339.93,41744
13,2024-11,17154393,8.25,12006921.41,8.40,10116770.67,1890150.74,15.74,314070.31,44971
14,2024-12,20825167,21.40,14602932.55,21.62,12286771.33,2316161.22,15.86,274583.03,54461
15,2025-01,14855680,-28.66,10405331.38,-28.74,8774856.01,1630475.37,15.67,253424.13,38937
16,2025-02,12368349,-16.74,8694838.47,-16.44,7325724.63,1369113.84,15.75,267007.52,32725
17,2025-03,15756344,27.39,11099870.99,27.66,9390144.35,1709726.64,15.40,203931.60,44273
18,2025-04,17732804,12.54,12392666.59,11.65,10575437.08,1817229.51,14.66,317611.67,50780
19,2025-05,18717526,5.55,13128154.65,5.93,11158350.33,1969804.32,15.00,315280.08,54290
20,2025-06,18191083,-2.81,12790797.86,-2.57,10839023.64,1951774.22,15.26,300667.22,52126
21,2025-07,19372063,6.49,13607163.80,6.38,11570670.56,2036493.24,14.97,322699.85,55348
22,2025-08,18848680,-2.70,13249355.63,-2.63,11257214.10,1992141.53,15.04,302479.14,54648
23,2025-09,14885032,-21.03,10453454.10,-21.10,8885397.60,1568056.50,15.00,226938.52,41569
24,2025-10,14296340,-3.95,10035892.24,-3.99,8414999.41,1620892.83,16.15,189588.89,37453
25,2025-11,16171174,13.11,11339661.96,12.99,9537559.08,1802102.88,15.89,243327.19,42307
26,2025-12,22244359,37.56,15635963.28,37.89,13132253.77,2503709.51,16.01,310839.83,58762
27,2026-01,15075762,-32.23,10616956.41,-32.10,8894539.84,1722416.57,16.22,247432.72,40138
28,2026-02,13521080,-10.31,9515984.18,-10.37,7962548.60,1553435.58,16.32,282745.68,35362
29,2026-03,17267550,27.71,12162736.98,27.81,10287749.61,1874987.37,15.42,229362.84,48201
30,2026-04,17356456,0.51,12262285.98,0.82,10349926.92,1912359.06,15.60,288878.04,50135
31,2026-05,20135170,16.01,14158935.16,15.47,12023749.78,2135185.38,15.08,311126.66,57685
32,2026-06,19491484,-3.20,13686003.19,-3.34,11658283.59,2027719.60,14.82,271236.45,56301
33,2026-07,20707626,6.24,14523747.10,6.12,12391342.72,2132404.38,14.68,280139.17,59539
34,2026-08,18845139,-8.99,13312040.63,-8.34,11226288.37,2085752.26,15.67,324820.87,54091
35,2026-09,15696483,-16.71,11055736.59,-16.95,9363029.16,1692707.43,15.31,205457.68,44198

In [15]:
# we have 36 months we need the YoY To split them into 3 years 12 months each 
First_year = sales_transactions.loc[
    (sales_transactions['Order_Date'] >= '2023-10-1') &
    (sales_transactions['Order_Date'] <= '2024-09-30')]
First_year['12_month_period'] = 'period 1'

Second_year = sales_transactions.loc[
    (sales_transactions['Order_Date'] >= '2024-10-1') &
    (sales_transactions['Order_Date'] <= '2025-09-30')]
Second_year['12_month_period'] = 'period 2'

Third_year = sales_transactions.loc[
    (sales_transactions['Order_Date'] >= '2025-10-1') &
    (sales_transactions['Order_Date'] <= '2026-09-30')]

Third_year['12_month_period'] = 'period 3'

All_Three_Years = pd.concat([First_year, Second_year, Third_year], ignore_index=True)
All_Three_Years

,Invoice_ID,Order_Date,Month_Key,Location_ID,Location_Name,Channel,Customer_ID,Customer_Type,Customer_Governorate,Product_ID,...,Gross_Profit_EGP,Gross_Margin_Pct,Payment_Method,Returned,Return_Date,Return_Reason,Refund_Value_EGP,Quality_Related_Return,Data_Class,12_month_period
0,INV0000001,2024-05-11,2024-05,LOC002,LEO MODA Online Store,Online,C18976,Retail,Cairo,P059,...,82.23,0.2493,Wallet,No,NaT,No return,0.0,No,Modeled training transaction anchored to publi...,period 1
1,INV0000004,2024-06-05,2024-06,LOC003,El-Sharnouby Wholesale Desk,Wholesale,C21377,Wholesale,Dakahlia,P004,...,907.59,0.0799,Bank Transfer,No,NaT,No return,0.0,No,Modeled training transaction anchored to publi...,period 1
2,INV0000008,2024-09-18,2024-09,LOC002,LEO MODA Online Store,Online,C13602,Retail,Alexandria,P024,...,82.94,0.3082,Card,Yes,2024-10-09,Size / fit,269.1,No,Modeled training transaction anchored to publi...,period 1
3,INV0000013,2024-08-02,2024-08,LOC001,LEO MODA - Sidi Bishr Store,Retail,C24130,Retail,Alexandria,P008,...,77.37,0.2616,Cash,No,NaT,No return,0.0,No,Modeled training transaction anchored to publi...,period 1
4,INV0000019,2024-02-02,2024-02,LOC002,LEO MODA Online Store,Online,C26041,Retail,Other,P049,...,161.65,0.4490,Wallet,No,NaT,No return,0.0,No,Modeled training transaction anchored to publi...,period 1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179995,INV0179991,2026-03-05,2026-03,LOC002,LEO MODA Online Store,Online,C28346,Retail,Alexandria,P045,...,276.32,0.3187,Card,No,NaT,No return,0.0,No,Modeled training transaction anchored to publi...,period 3
179996,INV0179993,2026-03-24,2026-03,LOC003,El-Sharnouby Wholesale Desk,Wholesale,C28338,Wholesale,Alexandria,P029,...,673.67,0.1399,Bank Transfer,No,NaT,No return,0.0,No,Modeled training transaction anchored to publi...,period 3
179997,INV0179996,2026-07-11,2026-07,LOC002,LEO MODA Online Store,Online,C19390,Retail,Other,P006,...,107.88,0.3875,Cash,No,NaT,No return,0.0,No,Modeled training transaction anchored to publi...,period 3
179998,INV0179999,2026-08-18,2026-08,LOC002,LEO MODA Online Store,Online,C24159,Retail,Cairo,P054,...,342.11,0.4409,Cash,No,NaT,No return,0.0,No,Modeled training transaction anchored to publi...,period 3
179999,INV0180000,2026-07-17,2026-07,LOC003,El-Sharnouby Wholesale Desk,Wholesale,C11646,Wholesale,Cairo,P003,...,1039.23,0.1383,Bank Transfer,No,NaT,No return,0.0,No,Modeled training transaction anchored to publi...,period 3

In [16]:
YoY_growth = All_Three_Years.pivot_table(
    index='12_month_period', values=['Gross_Sales_EGP'],
    aggfunc='sum').sort_index()

YoY_growth['Gross_Sales_EGP_Growth_Pct'] = round(YoY_growth['Gross_Sales_EGP'].pct_change() * 100, 2) 

agg_cols = ['Net_Sales_EGP', 'Estimated_COGS_EGP', 'Gross_Profit_EGP', 'Refund_Value_EGP', 'Quantity']
for col in agg_cols:
    agg_index='12_month_period'
    YoY_growth[col] = All_Three_Years.pivot_table(
                                    index=agg_index, values=[col],
                                    aggfunc='sum').sort_index()[col]
    YoY_growth[col] = round(YoY_growth[col], 2)
    if col == 'Net_Sales_EGP':
        YoY_growth[f'{col}_Growth_Pct'] = round(YoY_growth[col].pct_change() * 100, 2)
    if col == 'Gross_Profit_EGP':
        YoY_growth['Gross_Margin_Pct'] = round(YoY_growth['Gross_Profit_EGP'] / YoY_growth['Net_Sales_EGP'] * 100, 2)

YoY_growth.reset_index(inplace=True)
YoY_growth

,12_month_period,Gross_Sales_EGP,Gross_Sales_EGP_Growth_Pct,Net_Sales_EGP,Net_Sales_EGP_Growth_Pct,Estimated_COGS_EGP,Gross_Profit_EGP,Gross_Margin_Pct,Refund_Value_EGP,Quantity
0,period 1,184728652,NaN,1.295243e+08,NaN,1.097185e+08,19805835.80,15.29,2924016.53,510545
1,period 2,204554786,10.73,1.435081e+08,10.80,1.214893e+08,22018781.25,15.34,3318033.00,565872
2,period 3,210808623,3.06,1.483059e+08,3.34,1.252423e+08,23063672.85,15.55,3184956.02,584172