In [1]:
import pandas as pd
df = pd.read_csv('data/Titanic.csv')

In [2]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### Q_1: Create a Pandas Series named survival_series using the Survived column of the DataFrame

In [3]:
survival_series = df.Survived
survival_series

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

### Q_2: Display the last 3 rows of the DataFrame and check the data type of the Age column

In [4]:
df.tail(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [5]:
df.Age.dtype

dtype('float64')

### Q_3 :  Select the Name and Age columns, then filter rows where the passenger’s age is greater than 30

In [6]:
df.loc[df.Age > 30,['Name','Age']]

                                                  Name   Age
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
6                              McCarthy, Mr. Timothy J  54.0
11                            Bonnell, Miss. Elizabeth  58.0
..                                                 ...   ...
873                        Vander Cruyssen, Mr. Victor  47.0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0
881                                 Markun, Mr. Johann  33.0
885               Rice, Mrs. William (Margaret Norton)  39.0
890                                Dooley, Mr. Patrick  32.0

[305 rows x 2 columns]

### Q_4: Add a new column FamilySize to the DataFrame, calculated as SibSp + Parch + 1 (including the passenger themselves)

In [7]:
df['FamilySize'] = df.SibSp + df.Parch + 1
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1

#### Q_5: Fill missing values in the Age column with the mean age then Group the data by Pclass and calculate the average age for each class

In [8]:
df.fillna({'Age':df.Age.mean()},inplace=True)
df.groupby('Pclass')['Age'].mean()

Pclass
1    37.048118
2    29.866958
3    26.403259
Name: Age, dtype: float64

#### Q_Bonus: Calculate the survival rate (mean of Survived) for each gender (Sex)

In [19]:
df.groupby(['Sex','Pclass'])['Survived'].mean().unstack() * 100

Pclass          1          2          3
Sex
female  96.808511  92.105263  50.000000
male    36.885246  15.740741  13.544669

### Q_6: Split the Titanic DataFrame df into two parts: df1 (first 500 rows) and df2 (remaining rows). Concatenate them vertically to recreate the original DataFrame.

In [10]:
df1 = df.loc[:499,:]
df2 = df.loc[499:,:]
df3 = pd.concat([df1,df2])
df3.info()

<class 'pandas.DataFrame'>
Index: 892 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  892 non-null    int64
 1   Survived     892 non-null    int64
 2   Pclass       892 non-null    int64
 3   Name         892 non-null    str
 4   Sex          892 non-null    str
 5   Age          892 non-null    float64
 6   SibSp        892 non-null    int64
 7   Parch        892 non-null    int64
 8   Ticket       892 non-null    str
 9   Fare         892 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     890 non-null    str
 12  FamilySize   892 non-null    int64
dtypes: float64(2), int64(6), str(5)
memory usage: 97.6 KB

### Q_7: Create a new DataFrame passenger_details with columns PassengerId and Nationality. Perform a left join to merge it with df, keeping all original passengers.

In [11]:
passenger_details = pd.DataFrame(columns=['Nationality'])
passenger_details['Passengerid'] = df.PassengerId 
left_join = df.join(passenger_details,how='left').drop(columns='Passengerid')
left_join.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize,Nationality
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2,NaN
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,NaN
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,NaN
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2,NaN
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1,NaN

### Q_8 :  Group the data by Pclass and Sex, then calculate the average Age and total Fare for each group.

In [12]:
df.groupby(['Pclass','Sex']).aggregate({'Age':'mean','Fare':'sum'})

                     Age       Fare
Pclass Sex
1      female  34.141405  9975.8250
       male    39.287717  8201.5875
2      female  28.748661  1669.7292
       male    30.653908  2132.1125
3      female  24.068493  2321.1086
       male    27.372153  4393.5865

In [13]:
s_age = df.groupby(['Pclass','Sex'])['Age'].mean()
s_fare = df.groupby(['Pclass','Sex'])['Fare'].sum()
s_fare.rename('Total_Fare',inplace=True)
pd.concat([s_age,s_fare],axis=1)

                     Age  Total_Fare
Pclass Sex
1      female  34.141405   9975.8250
       male    39.287717   8201.5875
2      female  28.748661   1669.7292
       male    30.653908   2132.1125
3      female  24.068493   2321.1086
       male    27.372153   4393.5865