# Day 6

___

## Concate And Grouping

- Combining data from different sources is an important part of **data analysis**.
- Data can be combined using different operations:
  - **Concatenation:** Joining datasets together.
  - **Joins and Merges:** Combining datasets based on common columns or indexes.
- Pandas `Series` and `DataFrame` are designed to support data-combination operations.
- Pandas provides built-in functions and methods that make data wrangling:
  - Fast
  - Simple
  - Efficient
- `pd.concat()` is used for **simple concatenation** of `Series` and `DataFrame` objects.

In [1]:
import pandas as pd
import numpy as np

### Creating a DataFrame for Examples

- A custom function can be created to **generate a DataFrame** in a specific format.
- This makes it easier to create **consistent sample data** for examples.
- The function can be reused multiple times throughout the examples.
- It helps simplify demonstrations of Pandas operations.

In [21]:
def make_df(cols, ind): 
    """Quickly create a DataFrame.""" 
    data = {}
    for col in cols: 
        values = [] 
        for i in ind: 
            values.append(str(col) + str(i)) 
        data[col] = values 
    return pd.DataFrame(data, index=ind)

make_df('ABC', range(3))

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [ ]:
class display(object):
    """Display HTML representation of multiple objects"""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args
        
    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
                        for a in self.args)
    
    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                        for a in self.args)

### NP Concate:

#### 1D

In [24]:
x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 2D or more: Axis=1 Concate on Rows , Axis=0 Concate on Columns

In [27]:
x = [[1, 2],
     [3, 4]]
np.concatenate([x, x], axis=0)

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

### PD Concate:

- `pd.concat()` is used to **concatenate (combine) multiple `Series` or `DataFrame` objects**.
- It works similarly to NumPy's `np.concatenate()`.
- `pd.concat()` provides additional options that give more control over how data is combined.

#### Basic Syntax

```python
pd.concat(
    [obj1,obj2,..],
    axis=0,
    join='outer',
    ignore_index=False,
    keys=None,
    levels=None,
    names=None,
    verify_integrity=False,
    sort=False,
    copy=True
)

#### Important Parameters

- **`objs`** → The `Series` or `DataFrame` objects to combine.
- **`axis=0`** → Combine objects **row-wise (vertically)** | **`axis=1`** → Combine objects **column-wise (horizontally)**.
- **`join='outer'`** → Include all indexes or columns from the objects | **`join='outer'`** → Include common columns only.
- **`ignore_index=False`** → Keep the original indexes | **`ignore_index=True`** → Create a new sequential index.
- **`keys`** → Add labels to identify the original objects.
- **`sort=False`** → Keep the original column order.
- **`verify_integrity=False`** → Do not check for duplicate indexes | Set to **`True`** to check for duplicate indexes.

In [28]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6])

In [29]:
ser1

1    A
2    B
3    C
dtype: str

In [30]:
ser2

4    D
5    E
6    F
dtype: str

In [31]:
pd.concat([ser1, ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: str

In [10]:
df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [2, 4])
display('df1', 'df2', 'pd.concat([df1, df2])')

df1
    A   B
1  A1  B1
2  A2  B2

df2
    A   B
2  A2  B2
4  A4  B4

pd.concat([df1, df2])
    A   B
1  A1  B1
2  A2  B2
2  A2  B2
4  A4  B4

In [11]:
df3 = make_df('AB', [0, 1])
df4 = make_df('CD', [0, 1])
display('df3', 'df4', "pd.concat([df3, df4], axis=1)")

df3
    A   B
0  A0  B0
1  A1  B1

df4
    C   D
0  C0  D0
1  C1  D1

pd.concat([df3, df4], axis=1)
    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1

In [33]:
x = make_df('AB', [0, 1])
y = make_df('AB', [2, 3])
y.index = x.index  # make indices match
display('x', 'y', 'pd.concat([x, y])')

x
    A   B
0  A0  B0
1  A1  B1

y
    A   B
0  A2  B2
1  A3  B3

pd.concat([x, y])
    A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3

In [34]:
try:
    pd.concat([x, y], verify_integrity=True)
except ValueError as e:
    print("ValueError:", e)

ValueError: Indexes have overlapping values: Index([0, 1], dtype='int64')

In [35]:
display('x', 'y', 'pd.concat([x, y], ignore_index=True)')

x
    A   B
0  A0  B0
1  A1  B1

y
    A   B
0  A2  B2
1  A3  B3

pd.concat([x, y], ignore_index=True)
    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [36]:
display('x', 'y', "pd.concat([x, y], keys=['x', 'y'])")

x
    A   B
0  A0  B0
1  A1  B1

y
    A   B
0  A2  B2
1  A3  B3

pd.concat([x, y], keys=['x', 'y'])
      A   B
x 0  A0  B0
  1  A1  B1
y 0  A2  B2
  1  A3  B3

In [37]:
df5 = make_df('ABC', [1, 2])
df6 = make_df('BCD', [3, 4])
display('df5', 'df6', 'pd.concat([df5, df6])')

df5
    A   B   C
1  A1  B1  C1
2  A2  B2  C2

df6
    B   C   D
3  B3  C3  D3
4  B4  C4  D4

pd.concat([df5, df6])
     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4

In [40]:
display('df5', 'df6',"pd.concat([df5, df6], join='inner')")

df5
    A   B   C
1  A1  B1  C1
2  A2  B2  C2

df6
    B   C   D
3  B3  C3  D3
4  B4  C4  D4

pd.concat([df5, df6], join='inner')
    B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4

In [18]:
pd.concat([df5, df6.reindex(df5.columns, axis=1)])

     A   B   C
1   A1  B1  C1
2   A2  B2  C2
3  NaN  B3  C3
4  NaN  B4  C4

### Renaming

In [41]:
reviews = pd.read_csv("data/winemag-data-130k-v2.csv", index_col=0)

In [42]:
reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [44]:
reviews.rename(columns={'points': 'score'}).head()

,country,description,designation,score,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [45]:
reviews.rename(index={0: 'firstEntry', 1: 'secondEntry'}).head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
firstEntry,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
secondEntry,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [ ]:
reviews.rename_axis("wines", axis='rows').rename_axis("fields", axis='columns').head()
# 'rows' is accepted in pandas code but not officially documented in the type stubs thats why pylance/ flags it

fields,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
wines,,,,,,,,,,,,,
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

### Grouping

In [48]:
reviews.groupby('points').points.count()

points
80       397
81       692
82      1836
83      3025
84      6480
85      9530
86     12600
87     16933
88     17207
89     12226
90     15410
91     11359
92      9613
93      6489
94      3758
95      1535
96       523
97       229
98        77
99        33
100       19
Name: points, dtype: int64

In [51]:
reviews.groupby('points').price.min()

points
80      5.0
81      5.0
82      4.0
83      4.0
84      4.0
85      4.0
86      4.0
87      5.0
88      6.0
89      7.0
90      8.0
91      7.0
92     11.0
93     12.0
94     13.0
95     20.0
96     20.0
97     35.0
98     50.0
99     44.0
100    80.0
Name: price, dtype: float64

## Merge and Join

Relational Algebra

- **Relational Algebra** is a formal set of rules used to manipulate **relational data**.
- It is the conceptual foundation of many operations used in **databases**.
- It provides fundamental operations that can be combined to perform more complex data operations.
- Pandas implements several relational algebra operations through:
- **`pd.merge()`**
- **`join()`** method of `Series` and `DataFrame`
- These operations allow you to **combine and link data from different sources efficiently**.

### Merge

Categories of Merge

- `pd.merge()` supports **three main types of joins**:
  - **One-to-One**
  - **Many-to-One**
  - **Many-to-Many**
- All three types use the same `pd.merge()` function.
- The type of join depends on the **relationship between the data in the input DataFrames**.
- The basic syntax is: pd.merge(df1, df2)

#### One-to-One Merge

How `pd.merge()` Works

- `pd.merge()` automatically identifies the **common column** between the two DataFrames.
- In this example, both DataFrames contain an **`employee`** column.
- The `employee` column is used as the **key** to match the rows.
- The result is a **new DataFrame** containing information from both DataFrames.

Important Points

- The order of rows does **not need to be the same** in both DataFrames.
- `pd.merge()` matches rows based on the **key values**, not their positions.
- By default, the original **index is discarded** after merging.
- An exception occurs when merging based on the index using:
  - **`left_index=True`**
  - **`right_index=True`**

Main Idea

> `pd.merge()` combines DataFrames by matching values in a common key column, regardless of the original row order.

In [ ]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering',
                              'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})
display('df1', 'df2')

In [ ]:
df3 = pd.merge(df1, df2)
df3

#### Many-to-One Merge

- A **many-to-one join** occurs when one of the two DataFrames contains **duplicate values** in the key column.
- Multiple rows from one DataFrame can match a **single row** in the other DataFrame.
- `pd.merge()` preserves the duplicate entries in the resulting DataFrame.
- The matching is performed using the **common key column**.

Main Idea

- **Many rows** → match **one row**.
- Duplicate key values are **preserved** in the result.
- `pd.merge()` automatically combines the matching rows.

In [ ]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                    'supervisor': ['Carly', 'Guido', 'Steve']})
display('df3', 'df4', 'pd.merge(df3, df4)')

#### Many-to-Many Merge

- A **many-to-many join** occurs when the key column contains **duplicate values in both DataFrames**.
- Each matching key in the left DataFrame can be combined with **all matching keys** in the right DataFrame.
- This can produce **multiple rows for each matching key**.
- The resulting number of rows can increase significantly because of the multiple combinations.
- Many-to-many joins are useful when multiple records are associated with the same key.

Example Concept

- A DataFrame contains **people and their groups**.
- Another DataFrame contains **groups and their associated skills**.
- A many-to-many merge can be used to find the **skills associated with each person**.

Main Idea

> **Many-to-many:** Multiple rows in the left DataFrame match multiple rows in the right DataFrame.

In [ ]:
df5 = pd.DataFrame({'group': ['Accounting', 'Accounting',
                              'Engineering', 'Engineering', 'HR', 'HR'],
                    'skills': ['math', 'spreadsheets', 'software', 'math',
                               'spreadsheets', 'organization']})
display('df1', 'df5', "pd.merge(df1, df5)")

### Specification of the Merge Key

#### Merge Keys

- By default, `pd.merge()` looks for **common column names** in both DataFrames.
- The matching column is automatically used as the **merge key**.
- Sometimes, the column names in the two DataFrames are **different**.
- In this case, `pd.merge()` provides options to specify the columns that should be used as the merge keys.

Main Idea

- **Same column names** → `pd.merge()` can automatically identify the key.
- **Different column names** → Specify the merge keys explicitly.
- The main options for handling different key names are:
  - **`on`**
  - **`left_on`**
  - **`right_on`**
  - **`left_index`**
  - **`right_index`**

In [ ]:
display('df1', 'df2', "pd.merge(df1, df2, on='employee')")

In [ ]:
df3 = pd.DataFrame({'name': ['Jake', 'Bob', 'Sue', 'Sue'],
                    'salary': [70000, 80000, 120000, 90000]})
display('df1', 'df3', 'pd.merge(df1, df3, left_on="employee", right_on="name").drop("name",axis=1)')

In [ ]:
df1a = df1.set_index('employee')
df2a = df2.set_index('employee')
display('df1a', 'df2a')

In [ ]:
display('df1a', 'df2a',
        "pd.merge(df1a, df2a, left_index=True, right_index=True)")

#### join Keys

- Pandas provides the **`DataFrame.join()`** method as a convenient way to combine DataFrames.
- `join()` performs an **index-based merge** by default.
- Unlike `pd.merge()`, you do not need to specify the index columns using extra keywords.
- The rows are matched based on their **index values**.

In [ ]:
df1a

In [ ]:
df2a

In [ ]:
df1a.join(df2a)

#### Combining Indexes and Columns in `pd.merge()`

- `pd.merge()` allows you to combine **indexes and columns** when merging DataFrames.
- You can use the following combinations:
  - **`left_index=True` + `right_on='column'`**
  - **`left_on='column'` + `right_index=True`**
- This is useful when the merge key is stored as an **index in one DataFrame** and as a **column in the other DataFrame**.

In [ ]:
display('df1a', 'df3', "pd.merge(df1a, df3, left_index=True, right_on='name')")

### Specifying Set Arithmetic for Joins

#### Set Arithmetic in Joins

- When performing a join, an important consideration is **which key values should be included** in the result.
- A key value may exist in one DataFrame but **not in the other DataFrame**.
- Pandas provides different types of joins to control how these unmatched values are handled.

#### Main Join Types

- **Inner Join** → Keep only matching values from both DataFrames.
- **Outer Join** → Keep all values from both DataFrames.
- **Left Join** → Keep all values from the left DataFrame.
- **Right Join** → Keep all values from the right DataFrame.

#### Main Idea

> The type of join determines **which matching and non-matching records are kept** in the final DataFrame.

In [ ]:
df6 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
                    'food': ['fish', 'beans', 'bread']},
                   columns=['name', 'food'])
df7 = pd.DataFrame({'name': ['Mary', 'Joseph'],
                    'drink': ['wine', 'beer']},
                   columns=['name', 'drink'])
display('df6', 'df7', 'pd.merge(df6, df7)')

In [ ]:
pd.merge(df6, df7, how='inner')

In [ ]:
display('df6', 'df7', "pd.merge(df6, df7, how='outer')")

In [ ]:
display('df6', 'df7', "pd.merge(df6, df7, how='left')")

In [ ]:
display('df6', 'df7', "pd.merge(df6, df7, how='right')")

### Overlapping Column Names: The suffixes Keyword

#### Handling Conflicting Column Names

- Sometimes, the two DataFrames being merged contain **columns with the same name**.
- This can cause a conflict because Pandas needs to distinguish between the two columns.
- `pd.merge()` automatically handles these conflicts by adding **suffixes** to the column names.
- By default, Pandas uses:
  - **`_x`** → Column from the left DataFrame.
  - **`_y`** → Column from the right DataFrame.

In [ ]:
df8 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'rank': [1, 2, 3, 4]})
df9 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'rank': [3, 1, 4, 2]})
display('df8', 'df9', 'pd.merge(df8, df9, on="name")')

In [ ]:
pd.merge(df8, df9, on="name", suffixes=["_L", "_R"])

### Example: US States Data

In [ ]:
pop = pd.read_csv('state-population.csv')
areas = pd.read_csv('state-areas.csv')
abbrevs = pd.read_csv('state-abbrevs.csv')

display('pop.head()', 'areas.head()', 'abbrevs.head()')

In [ ]:
merged = pd.merge(pop, abbrevs, how='outer',
                  left_on='state/region', right_on='abbreviation').drop('abbreviation', axis=1)
merged.head()

In [ ]:
merged.isnull().any()

In [ ]:
merged[merged['population'].isnull()].head()

In [ ]:
merged.loc[merged['state'].isnull(), 'state/region'].unique()

In [ ]:
merged.loc[merged['state/region'] == 'PR', 'state'] = 'Puerto Rico'
merged.loc[merged['state/region'] == 'USA', 'state'] = 'United States'
merged.isnull().any()

In [ ]:
merged.head()

In [ ]:
final = pd.merge(merged, areas, on='state', how='left')
final.head()

In [ ]:
final.loc[final['state'] == 'United States','area (sq. mi)'] = final.loc[final['state'] != 'United States','area (sq. mi)'].unique().sum()

In [ ]:
final.isnull().any()

In [ ]:
final.loc[final['state'] == 'United States','population'].unique()

In [ ]:
final['state'][final['population'].isnull()].unique()

#### Handling Missing Values After a Merge

- Sometimes, a `DataFrame` may contain **missing (`NaN`) values** after a merge.
- In this example, the `areas` DataFrame does not contain the **area of the United States as a whole**.
- We could calculate the total area and add it to the DataFrame.
- However, the total area of the United States is **not relevant** to the current analysis.
- Therefore, we can remove the rows containing missing values using `dropna()`.

In [ ]:
final.isnull().any()

In [ ]:
final.dropna(inplace=True)
final.head()

In [ ]:
data2010 = final.query("year == 2010 & ages == 'total'")
data2010.head()

In [ ]:
data2010.set_index('state', inplace=True)
density = data2010['population'] / data2010['area (sq. mi)']

In [ ]:
density.sort_values(ascending=False, inplace=True)
density.head()

In [ ]:
density.tail()

## Aggregation and Grouping

### Aggregations in Pandas

- **Aggregation** is the process of summarizing a large dataset using a **single value** or a smaller set of values.
- Common aggregation functions include:
  - **`sum()`** → Calculates the total.
  - **`mean()`** → Calculates the average.
  - **`median()`** → Finds the middle value.
  - **`min()`** → Finds the smallest value.
  - **`max()`** → Finds the largest value.
- Pandas provides aggregation functions similar to those available in **NumPy**.
- Pandas also provides more advanced aggregation using **`groupby()`**.

#### Main Idea

> Aggregation helps us **summarize and understand large datasets** using useful statistics.

In [ ]:
import seaborn as sns
planets = sns.load_dataset('planets')
planets.shape

In [ ]:
planets.head()

In [ ]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.rand(5))
ser

In [ ]:
ser.sum()

In [ ]:
ser.mean()

In [ ]:
df = pd.DataFrame({'A': rng.rand(5),
                   'B': rng.rand(5)})
df

In [ ]:
df.mean()

By specifying the `axis` argument, you can instead aggregate within each row:

In [ ]:
df.mean(axis=0)

In [ ]:
planets.dropna().describe()

In [ ]:
planets.dropna().describe()

The following table summarizes some other built-in Pandas aggregations:

| Aggregation              | Returns                         |
|--------------------------|---------------------------------|
| ``count``                | Total number of items           |
| ``first``, ``last``      | First and last item             |
| ``mean``, ``median``     | Mean and median                 |
| ``min``, ``max``         | Minimum and maximum             |
| ``std``, ``var``         | Standard deviation and variance |
| ``mad``                  | Mean absolute deviation         |
| ``prod``                 | Product of all items            |
| ``sum``                  | Sum of all items                |

These are all methods of `DataFrame` and `Series` objects.

### groupby: Split, Apply, Combine

Simple aggregations can give you a flavor of your dataset, but often we would prefer to aggregate conditionally on some label or index: this is implemented in the so-called `groupby` operation.
The name "group by" comes from a command in the SQL database language, but it is perhaps more illuminative to think of it in the terms first coined by Hadley Wickham of Rstats fame: *split, apply, combine*.

A canonical example of this split-apply-combine operation, where the "apply" is a summation aggregation, is illustrated in this figure:

![](split-apply-combine.png)

([figure source in Appendix](https://github.com/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/06.00-Figure-Code.ipynb#Split-Apply-Combine))

This illustrates what the `groupby` operation accomplishes:

- The *split* step involves breaking up and grouping a `DataFrame` depending on the value of the specified key.
- The *apply* step involves computing some function, usually an aggregate, transformation, or filtering, within the individual groups.
- The *combine* step merges the results of these operations into an output array.

While this could certainly be done manually using some combination of the masking, aggregation, and merging commands covered earlier, an important realization is that *the intermediate splits do not need to be explicitly instantiated*. Rather, the `groupby` can (often) do this in a single pass over the data, updating the sum, mean, count, min, or other aggregate for each group along the way.
The power of the `groupby` is that it abstracts away these steps: the user need not think about *how* the computation is done under the hood, but rather can think about the *operation as a whole*.

As a concrete example, let's take a look at using Pandas for the computation shown in the following figure.
We'll start by creating the input `DataFrame`:

In [ ]:
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'data': range(6)}, columns=['key', 'data'])
df

In [ ]:
df.groupby('key')

In [ ]:
df.groupby('key').sum()

In [ ]:
planets.head()

In [ ]:
planets.groupby('method')

In [ ]:
planets.groupby('method')['orbital_period']

In [ ]:
planets.groupby('method')['orbital_period'].median()

In [ ]:
for (method, group) in planets.groupby('method'):
    print("method: {0:30s} shape={1}".format(method, group.shape))

### Dispatch methods

In [ ]:
planets['year'].describe()

In [ ]:
planets.groupby('method')['year'].describe()

### Aggregate, Filter, Transform, Apply

GroupBy Operations

- `groupby()` provides several operations for working with grouped data.
- In addition to **aggregation**, `GroupBy` objects support:
  - **`aggregate()`** → Apply one or more aggregation functions to each group.
  - **`filter()`** → Keep or remove groups based on a condition.
  - **`transform()`** → Perform calculations on each group and return results with the original shape.
  - **`apply()`** → Apply a custom function to each group.
- These operations allow us to perform different calculations **before combining the grouped data**.

Main Idea

> `GroupBy` provides several methods to efficiently process and analyze data **group by group**.

Common `GroupBy` Methods

| Method | Purpose |
|---|---|
| `aggregate()` | Calculate summary statistics for each group |
| `filter()` | Filter groups based on a condition |
| `transform()` | Transform values while keeping the original shape |
| `apply()` | Apply a custom function to each group |

- The following examples will use a specific `DataFrame` to demonstrate these operations.

In [ ]:
rng = np.random.RandomState(0)
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'data1': range(6),
                   'data2': rng.randint(0, 10, 6)},
                   columns = ['key', 'data1', 'data2'])
df

#### aggregate

In [ ]:
df.groupby('key').aggregate(['min', np.median, max])

In [ ]:
df.groupby('key').aggregate({'data1': 'min',
                             'data2': 'max'})

#### Filtering

In [ ]:
def filter_func(x):
    return x['data2'].std() > 4

display('df', "df.groupby('key').std()",
        "df.groupby('key').filter(filter_func)")

#### Transformation

In [ ]:
df

In [ ]:
def center(x):
    return x - x.mean()
df.groupby('key').transform(center)

#### apply

In [ ]:
df

In [ ]:
def norm_by_data2(x):
    # x is a DataFrame of group values
    x['data1'] /= x['data2'].sum()
    return x

df.groupby('key').apply(norm_by_data2)

### Specifying the Split Key

Group Specification in `groupby()`

- In simple examples, we used **one column** to define the groups.
- However, `groupby()` provides several ways to define groups.
- Groups can be created using:
  - A single column.
  - Multiple columns.
  - Other grouping criteria or functions.
- The way groups are defined determines **how the data is split** before applying an operation.

Main Idea

> `groupby()` is flexible and allows you to define groups in different ways depending on the analysis you need.

In [ ]:
df

In [ ]:
L = [0, 1, 0, 1, 2, 0] 
df.groupby(L).sum()

In [ ]:
df.groupby(df['key']).sum()

### A dictionary or series mapping index to group

Another method is to provide a dictionary that maps index values to the group keys:

In [ ]:
df2 = df.set_index('key')
mapping = {'A': 'vowel', 'B': 'consonant', 'C': 'consonant'}
display('df2', 'df2.groupby(mapping).sum()')

In [ ]:
df2.groupby(str.lower).mean()

### A list of valid keys

Further, any of the preceding key choices can be combined to group on a multi-index:

In [ ]:
df2.groupby([str.lower, mapping]).mean()

### Grouping Example

As an example of this, in a few lines of Python code we can put all these together and count discovered planets by method and by decade:

In [ ]:
decade = 10 * (planets['year'] // 10)
decade = decade.astype(str) + 's'
decade.name = 'decade'
planets.groupby(['method', decade])['number'].sum().unstack().fillna(0)

This shows the power of combining many of the operations we've discussed up to this point when looking at realistic datasets: we quickly gain a coarse understanding of when and how extrasolar planets were detected in the years after the first discovery.

I would suggest digging into these few lines of code and evaluating the individual steps to make sure you understand exactly what they are doing to the result.
It's certainly a somewhat complicated example, but understanding these pieces will give you the means to similarly explore your own data.